name: Build and Lipo pjsip with external libs for android
run-name: pjsip build for android 🚀

on: 
  push:
    branches: [ main, develop ]
  pull_request:
      types: [opened, synchronize, reopened]  
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: write
    steps:  
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build all archs
      run: |
        chmod +x ./android.sh
        sudo ./android.sh 
    - uses: actions/upload-artifact@v3
      with:
        name: lipjsua2-so
        path: ${{ github.workspace }}/output