name: Build and Lipo pjsip with external libs for ios
run-name: ${{ github.actor }} is building this 🚀

on:
  push:
    branches: [ main, develop ]
  pull_request:
      types: [opened, synchronize, reopened]  
      
jobs:
  build:
    runs-on: macos-latest
    permissions:
          contents: write
    steps:
    - name: install dependencies 
      run: brew install openssl@1.1 openh264 libvpx opencore-amr swig sipp nasm opus
    - uses: actions/checkout@v4
      with:
        repository: 'pjsip/pjproject'
        path: 'pjproject' 
    - name: config site
      run: cd ${{ github.workspace }}/pjproject/pjlib/include/pj && cp config_site_test.h config_site.h && echo "#define PJ_CONFIG_IPHONE 1" >> config_site.h && echo "#define PJMEDIA_HAS_VIDEO 1" >> config_site.h && echo "#define PJMEDIA_HAS_OPENH264_CODEC 1" >> config_site.h && echo "#define PJMEDIA_VIDEO_DEV_HAS_OPENGL 1" >> config_site.h && echo "#define PJMEDIA_VIDEO_DEV_HAS_OPENGL_ES 1" >> config_site.h && echo "#define PJMEDIA_VIDEO_DEV_HAS_IOS_OPENGL 1" >> config_site.h && echo "#include <OpenGLES/ES3/glext.h>" >> config_site.h
    - name: configure iphone
      run: |
        cd ${{ github.workspace }}/pjproject/
        MIN_IOS="-miphoneos-version-min=10.0" ARCH="-arch armv7" CFLAGS="-g -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openh264/include -DHAS_VID_CODEC_TEST=0 -fPIC" LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/openh264/lib -lstdc++" CXXFLAGS="-g -fPIC" --with-ssl=/usr/local/opt/openssl@1.1--with-openh264=/usr/local/opt/openh264 --with-opus=/usr/local/opt/opus ./configure-iphone
    - name: make
      run: make dep && make
    - name: swig bindings
      run: cd ${{ github.workspace }}/pjproject/pjsip-apps/src/swig && make