name: Build and Lipo pjsip with external libs for ios
run-name: ${{ github.actor }} is building this 🚀

on:
  push:
    branches: [ main, develop ]
  pull_request:
      types: [opened, synchronize, reopened]  
      
jobs:
  build:
    runs-on: macos-latest
    permissions:
          contents: write
    steps:
    - name: install dependencies 
      run: brew install openssl@1.1 openh264 libvpx opencore-amr swig sipp nasm opus
    - uses: actions/checkout@v4
      with:
        repository: 'pjsip/pjproject'
        path: 'pjproject' 
    - name: config site
      run: cd ${{ github.workspace }}/pjproject/pjlib/include/pj && cp config_site_test.h config_site.h && echo "#define PJ_CONFIG_IPHONE 1" >> config_site.h "#define PJMEDIA_HAS_VIDEO 1" >> config_site.h && echo "#define PJMEDIA_HAS_VID_TOOLBOX_CODEC 1" >> config_site.h
    - name: configure iphone armv7
      run: |
        cd ${{ github.workspace }}/pjproject/
        MIN_IOS="-miphoneos-version-min=10.0" ARCH="-arch armv7" CFLAGS="-g -I/usr/local/include -O2 -fembed-bitcode -fPIC" LDFLAGS="-O2 -fembed-bitcode -L/usr/local/lib -lstdc++" CXXFLAGS="-g -fPIC" ./configure-iphone
    - name: make armv7
      run: |
        cd ${{ github.workspace }}/pjproject/
        make dep && make
    - name: swig bindings
      run: cd ${{ github.workspace }}/pjproject/pjsip-apps/src/swig && make
    - name: configure iphone armv7s
      run: |
        cd ${{ github.workspace }}/pjproject/
        MIN_IOS="-miphoneos-version-min=10.0" ARCH="-arch armv7s" CFLAGS="-g -I/usr/local/include -O2 -fembed-bitcode -fPIC" LDFLAGS="-O2 -fembed-bitcode -L/usr/local/lib -lstdc++" CXXFLAGS="-g -fPIC" ./configure-iphone
    - name: make armv7s
      run: |
        cd ${{ github.workspace }}/pjproject/
        make dep && make
    - name: swig bindings
      run: cd ${{ github.workspace }}/pjproject/pjsip-apps/src/swig && make
    - name: configure iphone arm64
      run: |
        cd ${{ github.workspace }}/pjproject/
        MIN_IOS="-miphoneos-version-min=10.0" ARCH="-arch arm64" CFLAGS="-g -I/usr/local/include -O2 -fembed-bitcode -fPIC" LDFLAGS="-O2 -fembed-bitcode -L/usr/local/lib -lstdc++" CXXFLAGS="-g -fPIC" ./configure-iphone
    - name: make arm64
      run: |
        cd ${{ github.workspace }}/pjproject/
        make dep && make
    - name: swig bindings
      run: cd ${{ github.workspace }}/pjproject/pjsip-apps/src/swig && make
    - name: configure iphone i386
      run: |
        cd ${{ github.workspace }}/pjproject/
        MIN_IOS="-miphoneos-version-min=10.0" ARCH="-arch i386" CFLAGS="-g -I/usr/local/include -O2 -fembed-bitcode -fPIC" LDFLAGS="-O2 -fembed-bitcode -L/usr/local/lib -lstdc++" CXXFLAGS="-g -fPIC" ./configure-iphone
    - name: make x86
      run: | 
        cd ${{ github.workspace }}/pjproject/
        make dep && make
    - name: swig bindings
      run: cd ${{ github.workspace }}/pjproject/pjsip-apps/src/swig && make
    - name: configure iphone x86_64
      run: |
        cd ${{ github.workspace }}/pjproject/
        MIN_IOS="-miphoneos-version-min=10.0" ARCH="-arch x86_64" CFLAGS="-g -I/usr/local/include -O2 -fembed-bitcode -fPIC" LDFLAGS="-O2 -fembed-bitcode -L/usr/local/lib -lstdc++" CXXFLAGS="-g -fPIC" ./configure-iphone
    - name: make x86_64
      run: |
        cd ${{ github.workspace }}/pjproject/
        make dep && make
    - name: swig bindings
      run: cd ${{ github.workspace }}/pjproject/pjsip-apps/src/swig && make
    