name: Build and Lipo pjsip with external libs for ios
run-name: ${{ github.actor }} is building this 🚀

env:
  MIN_IOS_VERSION: '10.0'
  IOS_SDK_VERSION: '16.2'
  PJSIP_VERSION: '2.13.1'
  H264_VERSION: 'v2.0.0'
  DOWNLOAD_PJSIP_SRC: true
  CLEAN_PJSIP_SRC: true
  SSL_SUPPORT: false
  OPUS_SUPPORT: false
  H264_SUPPORT: false
  INDEPENDENT_WEBRTC: false
  ENABLE_ZRTP: false
  HAS_BITCODE: true
  HAS_IPV6: false
  

on:
  push:
    branches: [ main, develop ]
  pull_request:
      types: [opened, synchronize, reopened]  
      
jobs:
  instal_dependencies:
    runs-on: macos-latest
    permissions:
          contents: write
    steps:
    - name: install dependencies
      run: brew install swig sipp nasm
  clone_pjsip:
    runs-on: macos-latest
    permissions:
          contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'pjsip/pjproject'
        path: 'pjproject'
  clone_h264:
    runs-on: macos-latest
    permissions:
          contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'cisco/openh264'
          path: 'openh264'  
          ref: ${{ env.H264_VERSION }}
  clone_ssl:
    runs-on: macos-latest
    permissions:
          contents: write
    steps: 
    - uses: actions/checkout@v4
      with:
        repository: 'x2on/OpenSSL-for-iPhone'
        path: 'ssl'
  clone_opus:
    runs-on: macos-latest
    permissions:
          contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'xiph/opus'
        path: 'opus'
  show_files:
    runs-on: macos-latest
    permissions:
        contents: write
    steps:
      - name: show files
        run: ls ${{ github.workspace }} 