name: Build pjsua2 for ios
run-name: libpjsua2 builds 🚀

on: 
  push:
    branches: [ main, develop ]
  pull_request:
      types: [opened, synchronize, reopened]  
      
jobs:
  libpjsua2-ios:
    runs-on: macos-13
    name: iOS Build
    permissions:
          contents: write
    steps:
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build all ios archs
        run: |
          brew install nasm autoconf automake libtool swig
          sudo mv /Applications/Xcode_15.1.app /Applications/Xcode.app
          sed -i'' -e 's/xamarin/maui/g' ${{ github.workspace }}/pjproject/pjsip-apps/src/swig/csharp/Makefile
          ./build --ssl --opus --h264 -a=x86_64,arm64 --ci
      - uses: actions/upload-artifact@v3
        with:
          name: libpjsua2-ios
          path: ${{ github.workspace }}/libpjsua2