name: Build pjsua2 for ios
run-name: libpjsua2 builds 🚀

on: 
  push:
    branches: [ main, develop ]
  pull_request:
      types: [opened, synchronize, reopened]  
      
jobs:
  libpjsua2-ios:
    runs-on: macos-latest
    permissions:
          contents: write
    steps:  
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build all ios archs
        run: |
          brew install nasm autoconf automake libtool
          ./build --ssl --opus --h264 -A=x86_64,arnv7,arnv7s,arm64
      - uses: actions/upload-artifact@v3
        with:
          name: lipjsua2-ios
          path: ${{ github.workspace }}/lib