name: Release
run-name: Release libpjsua2 🚀

on: 
  push:
    tags:
      '*'
jobs:
  release:
    runs-on: self-hosted
    name: iOS Build
    permissions:
          contents: write
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Selecting Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Running Xcode version Is?
      run: /usr/bin/xcodebuild -version

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive 
    - name: build pjsip with opus bcg729 and h264
      run: |
        brew install nasm autoconf automake libtool swig
        sed -i'' -e 's/xamarin/maui/g' ${{ github.workspace }}/pjproject/pjsip-apps/src/swig/csharp/Makefile
        ./build h264 opus ssl bcg729 -a=x86_64,arm64 --ci
        tar -zcvf libpjsua2.tar.gz ./libpjsua2
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload ios artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./libpjsua2.tar.gz
        asset_name: libpjsua2.tar.gz
        asset_content_type: application/gzip